version: '3.9'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_TTL: ${REDIS_TTL}
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
      NODE_ENV: development
      IS_PUBLIC_KEY: ${IS_PUBLIC_KEY}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_EXPIRE_IN: ${JWT_EXPIRE_IN}
      JWT_REFRESH_EXPIRE_IN: ${JWT_REFRESH_EXPIRE_IN}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    command: sh -c "npx prisma generate && npm run start:dev"
    networks:
      my_custom_network:
        ipv4_address: ${APP_IP}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  my_custom_network:
    external: true